export const PLAYER_SEARCH = 'PLAYER_SEARCH';
export const PLAYER_SEARCH_SUCCESS = 'PLAYER_SEARCH_SUCCESS';
export const PLAYER_SEARCH_FAIL = 'PLAYER_SEARCH_FAIL';

export const RANK_TEAM = 'RANK_TEAM';
export const RANK_TEAM_SUCCESS = 'RANK_TEAM_SUCCESS';
export const RANK_TEAM_FAIL = 'RANK_TEAM_FAIL';

